### ISSUE TITLE
User Awareness

### ISSUE THREAD

**Issue by nitrag** [AdamEdgett/hubot-groupme#4]
Can you take a look at my code? I am not really good at debugging node yet. We need to modify the adapter so that it saves users into the "brain". Several external scripts aren't working because they need user awareness.

https://github.com/AdamEdgett/hubot-groupme/compare/master...nitrag:master

**Comment by AdamEdgett** [comment]
Cool. I'll take a look at the code
In the meantime do you want to open up a pull request with your current changes?

Also what's a good example script that depends on user awareness?

**Comment by nitrag** [comment]
I can't PR, my repo has a bug where I edited groupme.coffee, trying to
figure out what I did wrong. I was hoping you could copy/paste into your
code and debug on your end using my code as a guide. But maybe I'll figure
out my bug soon.

I'm trying to use:
https://www.npmjs.com/package/hubot-trivia-game

After a question is answered, it tries to grab and save to the user object
which fails. You wouldn't know this until you try and ask another
question...which it asks you the same one. So the function fails on the
user save and the game doesn't continue to the next question.
https://github.com/yincrash/hubot-trivia-game/blob/master/src/trivia-game.coffee
Lines 71-81 ^^

Also I can't seem to get any of the generic commands with <user> or <me> to
work -- I think due to hubot not saving (knowing) user objects.
Try some from the "hubot help" list. If they work for you then let me know.

**Comment by AdamEdgett** [comment]
I believe I successfully got it working using yours as a base.

I'm going to open up a pull request with yours so I can tack my changes onto it

**Comment by AdamEdgett** [comment]
Merged and published as 2.1.0
Lemme know if you have any problems with it

**Comment by AdamEdgett** [comment]
Also thanks for the report and help!

**Comment by nitrag** [comment]
You are the man!
